DOSKEY t=textpad $*
DOSKEY s="C:\Program Files\Sublime Text 3\sublime_text.exe" $*
DOSKEY ..=cd ..
DOSKEY ...=cd ../..
DOSKEY ....=cd ../../..
DOSKEY dt=cd C:\Users\flame\OneDrive\Desktop
DOSKEY dl=cd C:\Users\flame\OneDrive\Download
DOSKEY leet=cd C:\Users\flame\OneDrive\Desktop\2022\Leet2022
DOSKEY tools=cd C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools
DOSKEY web=cd C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools\webpageGen
DOSKEY regen=perl C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools\webpageGen\run.pl
DOSKEY parser=cd C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools\webparser
DOSKEY code=cd C:\Users\flame\OneDrive\Desktop\code
DOSKEY me=notepad C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools\alias.bat
DOSKEY reload=C:\Users\flame\OneDrive\Desktop\2022\Leet2022\tools\alias.bat
DOSKEY ls=dir $*
DOSKEY gs=git status
DOSKEY ga=git add *
DOSKEY gc=git commit -m $*
DOSKEY gp=git push
DOSKEY open=start $*
DOSKEY addall="git add -A"
DOSKEY commit=git commit -m  $*
DOSKEY fm="perl format.pl"
DOSKEY kc="taskkill /F /IM chrome.exe"
DOSKEY run=perl run.pl